use dan;


CREATE TABLE USER_ROLES(
    ID INT NOT NULL AUTO_INCREMENT, 
    UserType VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID)
);

INSERT INTO USER_ROLES (UserType) VALUES ('Admin');
INSERT INTO USER_ROLES (UserType) VALUES ('Customer');


CREATE TABLE PPL(
    PERSON_ID INT NOT NULL AUTO_INCREMENT, 
    First_Name VARCHAR(25) NOT NULL, 
    Second_Name VARCHAR(25) NOT NULL,
    Age INT,
    UserName VARCHAR(25) NOT NULL UNIQUE,
    Password VARCHAR(25) NOT NULL,
    Nationality INT NOT NULL,
    User_role INT NOT NULL,
    PRIMARY KEY (PERSON_ID),
    FOREIGN KEY (Nationality) REFERENCES COUNTRIES(COUNTRY_ID),
    FOREIGN KEY (User_role) REFERENCES USER_ROLES(ID)
);
